# Generated by Django 6.0.6 on 2026-06-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_add_mirror_subproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='preview_image',
            field=models.URLField(blank=True, help_text='URL screenshot for the card preview'),
        ),
    ]
