# Generated by Django 6.0.6 on 2026-06-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_add_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproject',
            name='preview_images',
        ),
        migrations.CreateModel(
            name='PreviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='previews/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.subproject')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
